<?php
use Phalcon\Tag;
?>
<?php
    echo Phalcon\Tag::javascriptInclude("js/jquery.min.js");
    echo Phalcon\Tag::javascriptInclude("javascript/jquery.js");
    echo Phalcon\Tag::stylesheetLink("css/pretraga.css");
    echo Phalcon\Tag::stylesheetLink("http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css", false);
    echo Phalcon\Tag::javascriptInclude("http://code.jquery.com/ui/1.10.3/jquery-ui.js", false);
    
    
?>


<script type="text/javascript">
   
    $(document).ready(function(){
      var opcija=1;
      $(document).tooltip();
      $("#mogucnosti").change(function(){
        
      var n = $(this).val();
      opcija = n;
      switch (n) {
        case '1':
            $("#2").fadeOut();
            $("#1").fadeIn();
            $("#loader").empty();
            $("#artupall").fadeOut();
            $("#loader").attr('title', '');
            break;
        case '2':
            $("#1").fadeOut();
            $("#2").fadeIn();
            $("#loader").empty();
            $("#artupall").fadeOut();
      }
      
      });
      
      
      //console.log($('#nesto').html());
      $('#nesto').dialog();
      $('#mogucnosti').menu();
      var sNumber = new Array();
      var sCode = new Array();
      var rCode = new Array();
      var gsCode = new Array();
      // ajax poziv za prikupljanje svih Shipment Numbera iz baze
      $.ajax({
        url: '<?php echo  $this->url->get("pretraga/getShipmentNumber");?>',
        type: 'POST',
        dataType: 'json',
        success: function(data){
            if (data==null) {
                return;
            }
            for (i=0; i<data.length; i++) {
                sNumber.push(data[i]);
            }
            
            $('#snumber').autocomplete({
                source: sNumber
                });
        },
        error: function(){
             alert("GRESKA: Neuspjesan JSON poziv.");
        }
      
      });
      
      
       $.ajax({
        url: '<?php echo  $this->url->get("pretraga/getSenderCode");?>',
        type: 'POST',
        dataType: 'json',
        success: function(data){
            if (data==null) {
                return;
            }
            for (i=0; i<data.length; i++) {
                sCode.push(data[i]);
            }
            
            $('#scode').autocomplete({
                source: sCode
                });
        },
        error: function(){
            alert("GRESKA: Neuspjesan JSON poziv.");
        }
      
      });
       
       
         $.ajax({
        url: '<?php echo  $this->url->get("pretraga/getReceiverCode");?>',
        type: 'POST',
        dataType: 'json',
        success: function(data){
            if (data==null) {
                return;
            }
            for (i=0; i<data.length; i++) {
                rCode.push(data[i]);
            }
            
            $('#rcode').autocomplete({
                source: rCode
                });
        },
        error: function(){
            alert("GRESKA: Neuspjesan JSON poziv.");
        }
      
      });
         
         // dobavljanje gs1_codova za autocomplete
         $.ajax({
        url: '<?php echo  $this->url->get("pretraga/getGS1Code");?>',
        type: 'POST',
        dataType: 'json',
        success: function(data){
            if (data==null) {
                return;
            }
            for (i=0; i<data.length; i++) {
                gsCode.push(data[i]);
            }
            
            $('#gscode').autocomplete({
                source: gsCode
                });
        },
        error: function(){
            alert("GRESKA: Neuspjesan JSON poziv.");
        }
      
      });
      
      
       
        $("#loader").fadeIn('600');
        $("#loader").append("<p id='poruka1'>Ovdje idu rezultati vase pretrage...</p>");
        
        
      

     $('.search').click(function(){
         
        var visina = $(document).height();
        $(document).scrollTop(visina*0.4);  
          if (opcija==1) {
            //$("#loader").addClass('loading');
            $("#loader").empty();
            $("#loader").append("<div id='lltest'> <div>");
           //alert("Unio si: " + dodatak);
           //$("#loader").fadeIn("200");
            var sNumber = $('#snumber').val();
            var sCode = $('#scode').val();
            var rCode = $('#rcode').val();
            
            $.ajax({
            url: '<?php echo  $this->url->get("pretraga/getPackingList");?>',
            type: 'POST',
            dataType: 'json',
            data: {sNumber:sNumber, sCode:sCode, rCode:rCode},
            success: function(data){
                if (data==null) {
                    $("#loader").empty();
                    $("#loader").append("<div id='greska'> </div>");
                    
                }
                else{
                 setTimeout(function(){
                //$("#loader").removeClass('loading');
                $("#loader").empty();
                $("#loader").append("<p id='naslov'>Rezultat pretrage: Order/Packing List</p><hr />");
                $("#loader").append("<table id='tab' border='1'/>");
                $("#loader table").append("<tr><th class='zag'>Shipment_Number</th><th class='zag'>Sender_Name</th><th class='zag'>Sender_Code</th><th class='zag'>Receiver_Name</th><th class='zag'>Receiver_Code</th></tr>");
                
                for (i=0; i<data.length; i++) {
                    //$("#loader").append("<p class='izlaz'>Ime: " + data[i].ime + "</p>" + "<p class='izlaz'>Prezime: " + data[i].prezime + "<br />");
                    
                    $("#loader table").append("<tr><td class='sadr1'>" + data[i].Shipment_Number + "</td><td class='sadr'>" + data[i].Sender_Name + "</td><td class='sadr'>" + data[i].Sender_Code + "</td>"+
                    "<td class='sadr'>" + data[i].Receiver_Name + "</td><td class='sadr'>" + data[i].Receiver_Code + "</td></tr>");   
                
                }
                },600);
                
            }
                
            },
            error: function(){
                alert("greska...");
            }
          });
          
          }
          else if (opcija==2) {
            $("#loader").attr('title', 'Mozete nastaviti pretrazivanje klikom na idPalete vrijednost.');
            var gsCode = $("#gscode").val();
            var iType = $("#itype").val();
            //alert("POdaci: " + gsCode + ", " + iType);
            $("#loader").empty();
            $("#loader").append("<div id='lltest'> <div>");
            // poziv za dobavljanje informacija o paletama
             $.ajax({
            url: '<?php echo  $this->url->get("pretraga/getPalete");?>',
            type: 'POST',
            dataType: 'json',
            data: {gsCode:gsCode, iType:iType},
            success: function(data){
                if (data==null) {
                    $("#loader").empty();
                    $("#loader").append("<div id='greska'> </div>");
                    
                }
                else{
                 setTimeout(function(){
                //$("#loader").removeClass('loading');
                $("#loader").empty();
                $("#loader").append("<p id='naslov'>Rezultat pretrage: Order/Palete</p><hr />");
                $("#loader").append("<table id='tab' border='1'/>");
                $("#loader table").append("<tr><th class='zag'>ID Palete</th><th class='zag'>GS1_Code</th><th class='zag'>Item_Type</th><th class='zag'>Order</th></tr>");
                
                for (i=0; i<data.length; i++) {
                    //$("#loader").append("<p class='izlaz'>Ime: " + data[i].ime + "</p>" + "<p class='izlaz'>Prezime: " + data[i].prezime + "<br />");
                    
                    $("#loader table").append("<tr><td id='palet' class='sadr1'>" + data[i].idPalete + "</td><td class='sadr'>" + data[i].GS1_Code + "</td><td class='sadr'>" + data[i].Item_Type + "</td><td class='sadr'>" + data[i].Order + "</td></tr>");   
                
                }
                },600);
                
            }
                
            },
            error: function(){
                alert("greska...");
            }
          });
           
           $("#gscode").val("");
           $("#itype").val();
            
          }
           $('#snumber').val("");
           $('#scode').val("");
           $('#rcode').val("");
          // $("#loader").empty();
        
       
        }) ;
     
     
     $("#loader").on("mouseenter", ".sadr1", function(){
        $(this).css('color', 'rgb(189,15,15)');
     });
     
      $("#loader").on("mouseleave", ".sadr1", function(){
        $(this).css('color', 'rgb(111,111,200)');
     });
      
    $("#loader").on("click", "#palet", function(){
        var idPalete = $(this).text();
        $("#artupall").fadeIn("400");
        //var pozicija = $(document).scrollTop();
        var visina = $(document).height();
        $(document).scrollTop(visina*0.8);
        
            $("#artupall").empty();
            $("#artupall").append("<div id='lltest'> <div>");
            // poziv za dobavljanje informacija o paletama
             $.ajax({
            url: '<?php echo  $this->url->get("pretraga/getArtupalsForPalete");?>',
            type: 'POST',
            dataType: 'json',
            data: {idPalete:idPalete},
            success: function(data){
                if (data==null) {
                    $("#artupall").empty();
                    $("#artupall").append("<div id='greska'> </div>");
                    
                }
                else{
                 setTimeout(function(){
                //$("#loader").removeClass('loading');
                $("#artupall").empty();
                $("#artupall").append("<p id='naslov'>Rezultat pretrage: Order/Palete/Artupal</p><hr />");
                $("#artupall").append("<table id='tab' border='1'/>");
                $("#artupall table").append("<tr><th class='zag'>Product_Code</th><th class='zag'>Description</th><th class='zag'>Lot_Number</th><th class='zag'>Quantity</th>"+
                                            "<th class='zag'>Unit_Of_Measure</th><th class='zag'>Count_Of_Units</th>"+"</tr>");
                
                for (i=0; i<data.length; i++) {
                    //$("#loader").append("<p class='izlaz'>Ime: " + data[i].ime + "</p>" + "<p class='izlaz'>Prezime: " + data[i].prezime + "<br />");
                    
                    $("#artupall table").append("<tr><td class='sadr'>" + data[i].Product_Code + "</td><td class='sadr'>" + data[i].Description + "</td><td class='sadr'>" + data[i].Lot_Number + "</td><td class='sadr'>" + data[i].Quantity + "</td>"+
                                                "<td class='sadr'>" + data[i].Unit_Of_Measure + "<td class='sadr'>" + data[i].Count_Of_Units + "</td>"+"</td>"+"</tr>");   
                
                }
                },600);
                
            }
                
            },
            error: function(){
                alert("greska...");
            }
          });
        
        
     });
    
    });
    
   
    
</script>


<p id="op">Parametar pretrage: <select id="mogucnosti">
    <option value="1" selected="1">Packing list</option>
    <option value="2">Palete</option>
    <option value="3">Artupal</option>
    <option value="4">Paketi</option>
    <option value="5">Micro</option>
    <option value="6">Jedinicno</option>
</select></p>

<div id="1" class="wrapper">
    
    <p id="nesto">Dobro dosli u panel za pretragu.</p>
 <div class="steps">
    <fieldset class="step">
        <legend>Search formular - Packing list</legend>
 <p>
    <label for="name">Shipment Number</label>
    <?php $opt = array('name', 'id'=>'snumber', 'size'=>'20');
      $buttopt = array('Show', 'id'=>'dugme','class'=>'klasa');
      $topt1 = array('surname', 'id'=>'scode', 'size'=>'20');
      $topt2 = array('email', 'id'=>'rcode', 'size'=>'20');
    ?>
    <?php echo Tag::textField($opt) ?>
 </p>
 <p>
    <label for="surname">Sender Code</label>
    <?php echo Tag::textField($topt1) ?>
   
 </p>
 <p>
    <label for="email">Receiver Code</label>
     <?php echo Tag::textField($topt2) ?>
 </p>
 
<input type="image" title="Pretraga..." class="search" src="/pobjeda/public/img/pretraga.jpg"
    </fieldset>
 </div>
 
  </div>

<div id="2" class="wrapper" style="display:none;">
 <div class="steps">
    <fieldset class="step">
        <legend>Search form - Palete</legend>
 <p>
    <label for="name">GS1 Code</label>
    <?php $opt = array('name', 'id'=>'gscode', 'size'=>'20');
      //$buttopt = array('Show', 'id'=>'dugme','class'=>'klasa');
      $topt1 = array('surname', 'id'=>'itype', 'size'=>'20');
      
    ?>
    <?php echo Tag::textField($opt) ?>
 </p>
 <p>
    <label for="surname">Item Type</label>
    <?php echo Tag::textField($topt1) ?>
   
 </p>
 
<input type="image" title="Pretraga..." class="search" src="/pobjeda/public/img/pretraga.jpg"
    </fieldset>
 </div>
 
  </div>
 
 <div id="loader">
 </div>
 
 <div id="artupall"></div>
 