<?php
use Phalcon\Tag;
?>
<?php
    echo Phalcon\Tag::javascriptInclude("http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js", false);
    echo Phalcon\Tag::javascriptInclude("javascript/jquery.js");
    echo Phalcon\Tag::stylesheetLink("css/test.css");
    echo Phalcon\Tag::stylesheetLink("http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css", false);
    echo Phalcon\Tag::javascriptInclude("http://code.jquery.com/ui/1.10.3/jquery-ui.js", false);
    //echo Phalcon\Tag::stylesheetLink("css/jquery-ui.css");
    //echo Phalcon\Tag::javascriptInclude("js/jquery-ui.js");
    
    
?>


<script type="text/javascript">
   
    $(document).ready(function(){
 
        $("#poruka").dialog();
    });
    
   
    
</script>

<p id="poruka" style="display:none">Dobro dosli na panel pretrage.</p>
<p>Sta ima kod vas</p>